### ISSUE TITLE
セリフオブジェクトの作成方法について

### ISSUE THREAD

**Issue by akazdayo** [manju-summoner/YukkuriMovieMaker4PluginSamples#4]
質問失礼します。

キャラクターのセリフをPlugin上で自動的に作成することは可能でしょうか？
例えば、test.mp3を追加した際に「テスト」とタイムラインに作成するなどが可能であれば、
作成方法を教えていただきたいです。

宜しくお願い致します。

**Comment by manju-summoner** [comment]
現状、プラグイン側からアイテムを追加することはできません。

他のアプリで作成した音声ファイルを元にボイスアイテムを生成したいということであれば、以下の方法でtest.mp3とtest.txtファイルからボイスアイテムを生成可能です。
https://manjubox.net/ymm4/faq/%E3%82%86%E3%81%A3%E3%81%8F%E3%82%8A%E3%83%9C%E3%82%A4%E3%82%B9/%E5%A4%96%E9%83%A8%E3%81%AE%E9%9F%B3%E5%A3%B0%E5%90%88%E6%88%90%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%B3%E3%81%A7%E4%BD%9C%E6%88%90%E3%81%97%E3%81%9F%E9%9F%B3%E5%A3%B0%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%9F%E3%81%84/

**Comment by akazdayo** [comment]
了解です。
お忙しい中、ご返信ありがとうございました。
